### ISSUE TITLE
Error reading netcdf file while running GrADSNcPlot in centos 7

### ISSUE THREAD

**Issue by netrajit** [ictp-esp/RegCM#2]
Following error occurs while running GrADSNcPlot.
	
[cdhmcom1@localhost REGCM_RUN]$ ./bin/GrADSNcPlot output/India-small_SRF.2020060100.nc 

Grid Analysis and Display System (GrADS) Version 2.2.0
Copyright (C) 1988-2017 by George Mason University
GrADS comes with ABSOLUTELY NO WARRANTY
See file COPYRIGHT for more information

Config: v2.2.0 little-endian readline grib2 netcdf hdf4-sds hdf5 opendap-grids,stn geotiff shapefile
Issue 'q config' and 'q gxconfig' commands for more detailed configuration information
GX Package Initialization: Size = 11 8.5 
Error: nc_open failed to open file output/India-small_SRF.2020060100.nc
NetCDF: Unknown file format
ga->

**Comment by graziano-giuliani** [comment]
This is a GrADS problem not being compiled with a recent netCDF library. The default output format from RegCM is CDF5 and is supported by netCDF since v 4.4 and is enabled by default when compiling netCDF library. Most probably the GrADS package you are using is compiled against an old netCDF library. You can anyway use nccopy program from the netCDF used to compile the RegCM model to change the netCDF CDF5 to any other on-disk supported netCDF format. Mind that if the model grid is big, then the netCDF format may restrict the possible choices of the target format. See the limits on the Table here: https://www.unidata.ucar.edu/software/netcdf/docs/file_structure_and_performance.html
